"""
Shoplytics: Association Rules API Router
Exposes market basket association rules generated by the Apriori Big Data algorithm.
"""

from typing import Optional, List
from fastapi import APIRouter, Depends, Query
from sqlalchemy.orm import Session
from ..database import get_db
from ..schemas import AssociationRuleResponse
from ..services.analytics_service import AnalyticsService

router = APIRouter(prefix="/api/association-rules", tags=["Association Rules"])


@router.get(
    "",
    response_model=List[AssociationRuleResponse],
    summary="List Association Rules",
    description="Retrieve Apriori association rules with optional thresholds for minimum support, confidence, and lift."
)
def list_association_rules(
    limit: int = Query(20, ge=1, le=100, description="Max rules to return"),
    min_support: Optional[float] = Query(None, ge=0.0, le=1.0, description="Minimum support threshold"),
    min_confidence: Optional[float] = Query(None, ge=0.0, le=1.0, description="Minimum confidence threshold"),
    min_lift: Optional[float] = Query(None, ge=0.0, description="Minimum lift threshold"),
    db: Session = Depends(get_db)
):
    return AnalyticsService.get_association_rules(
        db=db,
        limit=limit,
        min_support=min_support,
        min_confidence=min_confidence,
        min_lift=min_lift
    )


@router.get(
    "/top",
    response_model=List[AssociationRuleResponse],
    summary="Get Top Association Rules",
    description="Retrieve highest impact product association rules sorted by lift."
)
def get_top_rules(
    limit: int = Query(10, ge=1, le=100, description="Number of rules to return"),
    db: Session = Depends(get_db)
):
    return AnalyticsService.get_top_association_rules(db, limit=limit)
